# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Compile push

on:
  push:
  pull_request:

concurrency:
  group: compile-${{ github.workflow }}-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16' ]
    name: Build and Deploy on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: setup 'global-search'
        run: |
          ls -ltr
          mkdir -p ./dist
          cd global-search && npm install && npm run build
          cp -a dist/. ../dist/global-search

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: ./dist


      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: display branch name
        shell: bash
        run: echo "${{ steps.extract_branch.outputs.branch }}"

      - name: Publish
        uses: qld-gov-au/gha-publish-to-git@master
        with:
          repository: ${{ secrets.TARGET_REPO }}
          git_ref: '${{ github.ref }}'
          branch: '${{ steps.extract_branch.outputs.branch }}'
          github_token: '${{ secrets.GH_TOKEN }}'
          github_pat: '${{ secrets.GH_PAT }}'
          source_folder: dist
          tag_branch: main
        if: success()
